# AfEONet - Decap CMS Configuration
backend:
  name: git-gateway
  branch: main

# Development mode
local_backend: true

# Media settings
media_folder: "public/uploads"
public_folder: "/uploads"

# Production site configuration
site_url: "https://afeonet.africtivistes.com"
display_url: "https://afeonet.africtivistes.com"
logo_url: "/AfEONet-Logo-Green.jpeg"

# Collections configuration
collections:
  # News Articles Collection
  - name: "news"
    label: "News Articles"
    folder: "content/news"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "date", label: "Date", widget: "string" }
      - { name: "category", label: "Category", widget: "string" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "featured", label: "Featured", widget: "boolean", default: false }
      - { name: "image", label: "Image", widget: "string", required: false }
      - { name: "tags", label: "Tags", widget: "list", required: false }
      - { name: "body", label: "Content", widget: "markdown" }

  # Reports Collection
  - name: "reports"
    label: "Reports"
    folder: "content/reports"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - { name: "id", label: "Report ID", widget: "string" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "string" }
      - { name: "country", label: "Country", widget: "string" }
      - { name: "status", label: "Status", widget: "string" }
      - { name: "summary", label: "Summary", widget: "text" }
      - { name: "downloadUrl", label: "Download URL", widget: "string", required: false }
      - { name: "authors", label: "Authors", widget: "list", required: false }
      - { name: "tags", label: "Tags", widget: "list", required: false }
      - { name: "body", label: "Content", widget: "markdown" }

  # Alerts Collection
  - name: "alerts"
    label: "Security Alerts"
    folder: "content/alerts"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - { name: "id", label: "Alert ID", widget: "string" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "string" }
      - { name: "country", label: "Country", widget: "string" }
      - { name: "status", label: "Status", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "severity", label: "Severity", widget: "string" }
      - { name: "region", label: "Region", widget: "string" }
      - { name: "tags", label: "Tags", widget: "list", required: false }
      - { name: "body", label: "Content", widget: "markdown" }

  # About Sections Collection
  - name: "about"
    label: "About Sections"
    folder: "content/about"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "section", label: "Section", widget: "string" }
      - { name: "body", label: "Content", widget: "markdown" }